# Generated by Django 2.0.6 on 2018-07-01 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=1000, verbose_name='动态')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_creator', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_updater', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='人员')),
            ],
            options={
                'verbose_name': '人员动态',
                'verbose_name_plural': '人员动态',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('is_default', models.BooleanField()),
                ('remark', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '银行卡信息',
                'verbose_name_plural': '银行卡信息',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='获奖/证书名称')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '获奖/证书情况',
                'verbose_name_plural': '获奖/证书情况',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_creator', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_updater', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '员工评价',
                'verbose_name_plural': '员工评价',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=1000)),
                ('telephone', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='学校名称')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('education', models.IntegerField(choices=[(1, '本科'), (2, '专科'), (3, '硕士'), (4, '博士'), (5, '其他')], verbose_name='学历')),
                ('education_type', models.IntegerField(choices=[(1, '全日制'), (2, '非全日制'), (3, '自考'), (4, '专升本'), (5, '其他')], verbose_name='学历类型')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
            },
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_number', models.CharField(max_length=18)),
                ('residence_address', models.CharField(max_length=1000)),
                ('id_card_address', models.CharField(max_length=100)),
                ('id_card_photo', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '身份证信息',
                'verbose_name_plural': '身份证信息',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=100)),
                ('written_test_score', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interview_score', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '面试情况',
                'verbose_name_plural': '面试情况',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('technology', models.TextField(verbose_name='技术要点描述')),
                ('responsibility', models.TextField(verbose_name='个人负责工作')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目经历',
                'verbose_name_plural': '项目经历',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('native_place', models.CharField(max_length=100, verbose_name='籍贯')),
                ('nationality', models.CharField(max_length=100, verbose_name='民族')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('marital_status', models.IntegerField(choices=[(1, '单身'), (2, '恋爱中'), (3, '已婚'), (4, '离异'), (5, '其他')], verbose_name='婚姻状况')),
                ('target_position', models.CharField(max_length=100, verbose_name='求职意向')),
                ('expect_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='期望薪水（转正后）')),
                ('expect_salary_intern', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='期望薪水（实习期）')),
                ('telephone', models.CharField(max_length=100, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱地址')),
                ('qq', models.CharField(max_length=100, verbose_name='QQ号码')),
                ('wechat', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信号')),
                ('english_level', models.IntegerField(choices=[(1, 'CET4'), (2, 'CET6'), (3, 'IELTS'), (4, 'TOEFL'), (5, '其他')], verbose_name='英语证书最高等级')),
                ('english_score', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='英语证书最高成绩')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='身高（CM）')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='体重（公斤）')),
                ('introduction', models.TextField(verbose_name='自我评价')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '基本信息',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '熟练'), (2, '掌握'), (3, '熟悉'), (4, '了解')], verbose_name='技能水平')),
                ('content', models.CharField(max_length=100, verbose_name='技能描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '技能水平',
                'verbose_name_plural': '技能水平',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='单位名称')),
                ('position', models.CharField(max_length=100, verbose_name='职位/岗位')),
                ('description', models.TextField(verbose_name='工作内容描述')),
                ('resignation_reason', models.CharField(max_length=1000, verbose_name='离职原因')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
            },
        ),
    ]
