# Generated by Django 2.0.6 on 2018-07-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_trainingexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='birth_date',
            field=models.DateField(help_text='以身份证为准', verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='单位：cm', max_digits=12, null=True, verbose_name='身高'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='单位：公斤', max_digits=12, null=True, verbose_name='体重'),
        ),
    ]
