# Generated by Django 2.0.6 on 2018-07-08 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180707_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResume',
            fields=[
            ],
            options={
                'verbose_name': '面试简历',
                'verbose_name_plural': '面试简历',
                'proxy': True,
                'indexes': [],
            },
            bases=('employees.resume',),
        ),
        migrations.AlterModelOptions(
            name='trainingexperience',
            options={'verbose_name': '培训经历', 'verbose_name_plural': '培训经历'},
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(default='2018-01-01', verbose_name='日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
