# Generated by Django 2.0.6 on 2018-07-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20180719_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(help_text='正式员工工号以1开头，实习生以2开头，研究生以3开头，培训生以4开头，其他人以5开头，长度暂定5位', max_length=100, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='id_card_photo',
            field=models.ImageField(upload_to='profile', verbose_name='身份证正反面扫描图'),
        ),
    ]
