# Generated by Django 2.0.6 on 2018-07-31 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_progrom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progrom',
            name='user',
        ),
    ]
