# Generated by Django 2.0.6 on 2018-08-07 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0010_remove_progrom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='日报标题')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('report_content', tinymce.models.HTMLField(verbose_name='日报内容')),
                ('assess', tinymce.models.HTMLField(verbose_name='评价内容')),
                ('score', models.IntegerField(choices=[(1, '很差'), (2, '差'), (3, '一般'), (4, '好'), (5, '很好')], verbose_name='评价等级')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '人员报表',
                'verbose_name': '人员报表',
            },
        ),
        migrations.CreateModel(
            name='RegularMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='例会标题')),
                ('participant', models.CharField(max_length=500, verbose_name='例会标题')),
                ('meeting_time', models.DateTimeField(verbose_name='例会时间')),
                ('main_content', tinymce.models.HTMLField(verbose_name='例会主要内容')),
                ('enclosure', models.FileField(upload_to='./upload/', verbose_name='附件')),
                ('specker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
            ],
            options={
                'verbose_name_plural': '技术分享',
                'verbose_name': '技术分享',
            },
        ),
        migrations.CreateModel(
            name='WorkProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('key_skill', models.TextField(verbose_name='技术要点')),
                ('start_time', models.DateField(verbose_name='开始日期')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束日期')),
            ],
            options={
                'verbose_name_plural': '项目信息',
                'verbose_name': '项目信息',
            },
        ),
        migrations.DeleteModel(
            name='Progrom',
        ),
        migrations.AlterField(
            model_name='salary',
            name='actual_salary',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='实发工资'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='应发工资'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_level',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='工资标准'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_proportion',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='工资比例'),
        ),
    ]
